"""Conteúdo declarativo adicional do primeiro catálogo narrativo."""

# Serviço militar não entra no catálogo até existir uma configuração confiável
# por país (idade, obrigatoriedade e exceções), evitando regras inventadas.

EXPANDED_NARRATIVE_EVENTS = {
    "teammate_sides": {"key": "teammate_sides", "type": "dressing_room", "rarity": "rare", "unique": True,
        "title": "O elenco escolheu um lado", "text": "A briga recente dividiu parte do elenco.",
        "conditions": {"required_flags": ["public_locker_room_conflict"], "status": "active"},
        "choices": [{"id": "rebuild", "label": "Reconstruir o ambiente", "effects": {"reputation": {"locker_room": 5, "leadership": 2}, "history": "Você tentou reconstruir o ambiente após a divisão no elenco."}},
                    {"id": "isolate", "label": "Se afastar do grupo", "effects": {"reputation": {"locker_room": -6, "controversy": 3}, "behavior": {"locker_room_conflicts": 1}}}]},
    "rookie_arrival": {"key": "rookie_arrival", "type": "dressing_room", "rarity": "common", "cooldown": 18,
        "title": "Novato chegou ao elenco", "text": "Um jovem atleta começa a treinar com o grupo profissional.", "conditions": {"status": "active"},
        "choices": [{"id": "welcome", "label": "Ajudá-lo a se adaptar", "effects": {"reputation": {"locker_room": 4, "leadership": 3}}},
                    {"id": "ignore", "label": "Ignorar", "effects": {}},
                    {"id": "order_gear", "label": "Mandá-lo carregar seus equipamentos", "effects": {"reputation": {"locker_room": -3, "leadership": 1}, "behavior": {"authoritarian_choices": 1}}}]},
    "armband_dispute": {"key": "armband_dispute", "type": "dressing_room", "rarity": "uncommon", "cooldown": 22,
        "title": "Disputa pela braçadeira", "text": "O treinador define outro capitão para a próxima sequência de jogos.",
        "conditions": {"min_reputation": {"leadership": 10}, "min_matches": 8, "status": "active"},
        "choices": [{"id": "accept", "label": "Aceitar a decisão do treinador", "effects": {"reputation": {"discipline": 3, "locker_room": 1}}},
                    {"id": "ask", "label": "Cobrar a braçadeira", "effects": {"reputation": {"leadership": 2, "controversy": 2}}},
                    {"id": "claim_leader", "label": "Dizer publicamente que é o verdadeiro líder", "effects": {"reputation": {"leadership": 3, "locker_room": -5, "controversy": 9, "discipline": -3}, "behavior": {"authoritarian_choices": 1}}}]},
    "squad_clique": {"key": "squad_clique", "type": "dressing_room", "rarity": "uncommon", "cooldown": 20,
        "title": "Panelinha no elenco", "text": "Um grupo interno influencia o ambiente do vestiário.", "conditions": {"status": "active"},
        "choices": [{"id": "join", "label": "Se aproximar", "effects": {"reputation": {"locker_room": 2, "leadership": -1}}},
                    {"id": "neutral", "label": "Ficar neutro", "effects": {}},
                    {"id": "confront", "label": "Confrontar a panelinha", "effects": {"reputation": {"locker_room": -4, "leadership": 3, "controversy": 3}}}]},
    "reporter_aftermath": {"key": "reporter_aftermath", "type": "media", "rarity": "uncommon", "unique": True,
        "title": "A imprensa não esqueceu", "text": "A polêmica com o repórter volta a ser assunto em uma coletiva.",
        "conditions": {"required_flags": ["reporter_conflict"], "status": "active"},
        "choices": [{"id": "apologize", "label": "Pedir desculpas", "effects": {"reputation": {"media": 5, "controversy": -3}}},
                    {"id": "reignite", "label": "Manter o confronto", "effects": {"reputation": {"media": -6, "controversy": 5, "discipline": -2}, "behavior": {"media_conflicts": 1}}}]},
    "provocative_question": {"key": "provocative_question", "type": "media", "rarity": "common", "cooldown": 10,
        "title": "Pergunta provocativa após uma derrota", "text": "Após um resultado ruim, uma pergunta coloca sua atuação em xeque.", "conditions": {"max_form": 62, "status": "active"},
        "choices": [{"id": "take_responsibility", "label": "Assumir a responsabilidade", "effects": {"reputation": {"media": 3, "leadership": 2}}},
                    {"id": "blame_team", "label": "Culpar o time", "effects": {"reputation": {"media": -2, "locker_room": -4, "controversy": 3}}},
                    {"id": "blame_coach", "label": "Culpar o treinador", "effects": {"reputation": {"media": -4, "locker_room": -2, "controversy": 6, "discipline": -3}}}]},
    "became_meme": {"key": "became_meme", "type": "media", "rarity": "uncommon", "cooldown": 18,
        "title": "Virou meme", "text": "Um lance e uma declaração sua rendem brincadeiras nas redes e na imprensa.", "conditions": {"status": "active"},
        "choices": [{"id": "join_joke", "label": "Entrar na brincadeira", "effects": {"reputation": {"fans": 3, "media": 3}}},
                    {"id": "complain", "label": "Reclamar publicamente", "effects": {"reputation": {"controversy": 4, "media": -2}}},
                    {"id": "ignore", "label": "Ignorar", "effects": {}}]},
    "commercial_invitation": {"key": "commercial_invitation", "type": "media", "rarity": "uncommon", "cooldown": 26,
        "title": "Chamado para fazer um comercial", "text": "Uma marca convida você para uma campanha simples.", "conditions": {"min_overall": 68, "min_matches": 10, "status": "active"},
        "choices": [{"id": "accept", "label": "Aceitar", "effects": {"reputation": {"media": 3, "fans": 2}}},
                    {"id": "focus", "label": "Recusar para focar no futebol", "effects": {"reputation": {"discipline": 2}}},
                    {"id": "demand_more", "label": "Exigir um cachê maior", "effects": {"reputation": {"controversy": 2, "media": -1}}}]},
    "ishowspeed_video": {"key": "ishowspeed_video", "type": "media", "rarity": "very_rare", "unique": True,
        "title": "Convite para gravar com IShowSpeed", "text": "Um convite inesperado chega para participar de um vídeo esportivo.",
        "conditions": {"min_overall": 76, "min_matches": 25, "excluded_countries": ["Argentina"], "status": "active"},
        "choices": [{"id": "participate", "label": "Participar", "effects": {"reputation": {"fans": 5, "media": 4}}},
                    {"id": "decline", "label": "Recusar", "effects": {}}]},
    "tattoo": {"key": "tattoo", "type": "personal_life", "rarity": "common", "cooldown": 30,
        "title": "Ideia de tatuagem", "text": "Você pensa em marcar uma fase importante da vida fora de campo.", "conditions": {"min_age": 18, "status": "active"},
        "choices": [{"id": "small", "label": "Fazer uma tatuagem pequena", "effects": {"reputation": {"fans": 1}}},
                    {"id": "bold", "label": "Fazer uma tatuagem chamativa", "effects": {"reputation": {"fans": 2, "media": 1}}},
                    {"id": "cancel", "label": "Desistir", "effects": {}}]},
    "school_completion": {"key": "school_completion", "type": "personal_life", "rarity": "uncommon", "unique": True,
        "title": "Completar o ensino médio", "text": "A rotina entre estudos e futebol exige uma decisão importante.", "conditions": {"min_age": 16, "max_age": 19, "status": "active"},
        "choices": [{"id": "continue_studying", "label": "Continuar estudando", "effects": {"reputation": {"discipline": 3}, "history": "Você concluiu uma etapa importante dos estudos."}},
                    {"id": "football_only", "label": "Focar completamente no futebol", "effects": {"reputation": {"leadership": 1}}}]},
    "stalker_training": {"key": "stalker_training", "type": "personal_life", "rarity": "rare", "unique": True,
        "title": "Stalker apareceu nos treinos", "text": "Uma pessoa passa a aparecer repetidamente nos arredores dos treinos.", "conditions": {"min_overall": 65, "status": "active"},
        "choices": [{"id": "ignore", "label": "Ignorar", "effects": {"player": {"morale": -2}, "set_flags": ["stalker_ignored"], "follow_ups": [{"event_key": "stalker_residence", "after_weeks": 4}]}},
                    {"id": "tell_club", "label": "Avisar o clube", "effects": {"reputation": {"discipline": 2}, "set_flags": ["stalker_reported"]}},
                    {"id": "seek_authorities", "label": "Procurar segurança e autoridades", "effects": {"reputation": {"discipline": 3}, "set_flags": ["stalker_reported"]}}]},
    "stalker_residence": {"key": "stalker_residence", "type": "personal_life", "rarity": "very_rare", "unique": True,
        "title": "O stalker descobriu onde você mora", "text": "A situação passa a preocupar também fora do clube.", "conditions": {"required_flags": ["stalker_ignored"], "status": "active"},
        "choices": [{"id": "call_security", "label": "Reforçar a segurança", "effects": {"player": {"morale": -3}, "set_flags": ["stalker_residence_known"], "follow_ups": [{"event_key": "stalker_home_invasion", "after_weeks": 3}]}},
                    {"id": "report_now", "label": "Fazer uma denúncia", "effects": {"player": {"morale": -1}, "set_flags": ["stalker_reported"]}}]},
    "stalker_home_invasion": {"key": "stalker_home_invasion", "type": "personal_life", "rarity": "very_rare", "unique": True,
        "title": "Invasão de residência", "text": "A situação exige apoio imediato das autoridades. Você está em segurança, mas abalado.", "conditions": {"required_flags": ["stalker_residence_known"], "status": "active"},
        "choices": [{"id": "recover", "label": "Priorizar a recuperação", "effects": {"player": {"morale": -10, "form": -5}, "reputation": {"media": 1}, "history": "Você se afastou por alguns dias após uma invasão de residência."}}]},
    "teammate_spouse_affair": {"key": "teammate_spouse_affair", "type": "scandal", "rarity": "very_rare", "unique": True,
        "title": "Escândalo no elenco", "text": "Rumores sobre sua vida pessoal envolvem a família de um companheiro.", "conditions": {"min_age": 18, "status": "active"},
        "choices": [{"id": "deny", "label": "Negar tudo", "effects": {"reputation": {"locker_room": -7, "media": -2, "controversy": 5}, "set_flags": ["affair_denied"], "follow_ups": [{"event_key": "leaked_messages", "after_weeks": 4}]}},
                    {"id": "apologize", "label": "Admitir e pedir desculpas", "effects": {"reputation": {"locker_room": -5, "media": 1, "controversy": 3}, "set_flags": ["affair_admitted"], "follow_ups": [{"event_key": "teammate_exit_crisis", "after_weeks": 5}]}},
                    {"id": "assume", "label": "Assumir publicamente", "effects": {"reputation": {"locker_room": -10, "media": -4, "controversy": 10, "discipline": -4}}}]},
    "leaked_messages": {"key": "leaked_messages", "type": "scandal", "rarity": "rare", "unique": True,
        "title": "Mensagens vazaram", "text": "A polêmica ganha novo fôlego após mensagens privadas se tornarem públicas.", "conditions": {"required_flags": ["affair_denied"], "status": "active"},
        "choices": [{"id": "apologize_late", "label": "Pedir desculpas", "effects": {"reputation": {"media": 2, "locker_room": -2, "controversy": -2}}},
                    {"id": "attack_leak", "label": "Atacar quem vazou", "effects": {"reputation": {"media": -5, "controversy": 5, "discipline": -2}}}]},
    "teammate_exit_crisis": {"key": "teammate_exit_crisis", "type": "dressing_room", "rarity": "rare", "unique": True,
        "title": "Crise no elenco", "text": "O companheiro envolvido pede para se afastar e o ambiente fica ainda mais difícil.", "conditions": {"required_flags": ["affair_admitted"], "status": "active"},
        "choices": [{"id": "respect", "label": "Respeitar o momento", "effects": {"reputation": {"locker_room": 1, "leadership": 1}}},
                    {"id": "speak_out", "label": "Falar publicamente", "effects": {"reputation": {"locker_room": -4, "controversy": 4}}}]},
    "gambling_all_salary": {"key": "gambling_all_salary", "type": "scandal", "rarity": "rare", "cooldown": 34,
        "title": "Perda grande em apostas", "text": "A reincidência nas apostas cria uma preocupação séria fora de campo.", "conditions": {"min_behavior": {"gambling_incidents": 1}, "status": "active"},
        "choices": [{"id": "seek_help", "label": "Procurar ajuda", "effects": {"player": {"morale": -3}, "reputation": {"discipline": 2}, "set_flags": ["gambling_help"]}},
                    {"id": "hide_problem", "label": "Esconder o problema", "effects": {"player": {"morale": -6}, "reputation": {"controversy": 5, "discipline": -5}, "behavior": {"gambling_incidents": 1}}}]},
    "tax_investigation": {"key": "tax_investigation", "type": "scandal", "rarity": "very_rare", "unique": True,
        "title": "Investigação fiscal", "text": "Você é informado sobre uma apuração relacionada a documentos financeiros.", "conditions": {"min_age": 21, "min_overall": 70, "status": "active"},
        "choices": [{"id": "regularize", "label": "Regularizar a situação", "effects": {"reputation": {"discipline": 2, "media": 1}}},
                    {"id": "blame_advisors", "label": "Culpar responsáveis financeiros", "effects": {"reputation": {"media": -1, "controversy": 2}}},
                    {"id": "deny", "label": "Negar tudo", "effects": {"reputation": {"media": -4, "controversy": 6, "discipline": -3}, "set_flags": ["tax_denial"], "follow_ups": [{"event_key": "tax_investigation_advances", "after_weeks": 8}]}}]},
    "tax_investigation_advances": {"key": "tax_investigation_advances", "type": "scandal", "rarity": "rare", "unique": True,
        "title": "A investigação avançou", "text": "A apuração segue após sua negativa pública.", "conditions": {"required_flags": ["tax_denial"], "status": "active"},
        "choices": [{"id": "cooperate", "label": "Cooperar", "effects": {"reputation": {"discipline": 2, "controversy": -2}}},
                    {"id": "remain_silent", "label": "Evitar declarações", "effects": {"reputation": {"media": -2, "controversy": 3}}}]},
    "fake_passport": {"key": "fake_passport", "type": "scandal", "rarity": "legendary", "unique": True, "disabled": True,
        "disabled_reason": "Aguarda um sistema confiável de viagens internacionais.", "title": "Documento irregular em viagem", "text": "Indisponível sem contexto de viagem.",
        "conditions": {"international_travel": True, "status": "active"}, "choices": []},
    "criminal_investigation": {"key": "criminal_investigation", "type": "scandal", "rarity": "legendary", "unique": True,
        "title": "Nome citado em investigação", "text": "Seu nome foi citado em uma investigação envolvendo pessoas ligadas ao crime organizado.", "conditions": {"min_age": 21, "min_reputation": {"controversy": 25}, "status": "active"},
        "choices": [{"id": "deny", "label": "Negar envolvimento", "effects": {"reputation": {"media": -5, "controversy": 5, "discipline": -2}}},
                    {"id": "cooperate", "label": "Colaborar com a investigação", "effects": {"reputation": {"media": 1, "discipline": 3}}},
                    {"id": "no_comment", "label": "Evitar declarações públicas", "effects": {"reputation": {"media": -2, "controversy": 2}}}]},
    "team_bus_attack": {"key": "team_bus_attack", "type": "scandal", "rarity": "very_rare", "unique": True,
        "title": "Ônibus do time foi alvo de ataque", "text": "Após uma fase difícil, o deslocamento da equipe é interrompido por um incidente grave. Não há feridos.", "conditions": {"max_form": 48, "max_reputation": {"fans": -20}, "status": "active"},
        "choices": [{"id": "support_group", "label": "Apoiar o grupo", "effects": {"player": {"morale": -4, "form": -2}, "reputation": {"fans": 1, "leadership": 2}, "history": "Você viveu um incidente grave no deslocamento da equipe."}}]},
    "supporters_training_invasion": {"key": "supporters_training_invasion", "type": "scandal", "rarity": "rare", "cooldown": 30,
        "title": "Torcida invadiu o treino", "text": "Torcedores insatisfeitos interrompem a atividade para cobrar uma reação.", "conditions": {"max_form": 55, "max_reputation": {"fans": -12}, "status": "active"},
        "choices": [{"id": "talk", "label": "Conversar com os torcedores", "effects": {"reputation": {"fans": 4, "leadership": 2}}},
                    {"id": "leave", "label": "Sair do campo", "effects": {"reputation": {"fans": -2}}},
                    {"id": "confront", "label": "Confrontá-los", "effects": {"reputation": {"fans": -6, "controversy": 5, "discipline": -2}}}]},
    "fan_song": {"key": "fan_song", "type": "supporters", "rarity": "uncommon", "unique": True,
        "title": "A torcida criou uma música para você", "text": "Seu bom momento inspira uma homenagem nas arquibancadas.", "conditions": {"min_reputation": {"fans": 18}, "min_matches": 12, "status": "active"},
        "choices": [{"id": "thank", "label": "Agradecer à torcida", "effects": {"reputation": {"fans": 5}, "history": "A torcida criou uma música em sua homenagem."}}]},
    "health_diagnosis": {"key": "health_diagnosis", "type": "health", "rarity": "very_rare", "unique": True,
        "title": "Diagnóstico de saúde", "text": "Exames apontam uma condição que exige cuidados e uma pausa respeitosa na rotina.", "conditions": {"min_age": 18, "status": "active"},
        "choices": [{"id": "treat", "label": "Seguir o tratamento", "effects": {"player": {"morale": -5, "form": -4}, "history": "Você interrompeu temporariamente a rotina para cuidar da saúde."}},
                    {"id": "leave_for_health", "label": "Encerrar a carreira para cuidar da saúde", "effects": {"terminal": {"type": "retirement", "reason": "Você encerrou a carreira profissional para priorizar a saúde."}}}]},
    "disabling_accident": {"key": "disabling_accident", "type": "health", "rarity": "legendary", "unique": True,
        "title": "Acidente incapacitante", "text": "Um acidente grave fora de campo torna impossível seguir no futebol profissional.", "conditions": {"min_age": 18, "status": "active"},
        "choices": [{"id": "accept_retirement", "label": "Encerrar a carreira", "effects": {"terminal": {"type": "retirement", "reason": "Um acidente incapacitante encerrou sua carreira profissional."}}}]},
    "plane_crash": {"key": "plane_crash", "type": "health", "rarity": "legendary", "unique": True, "disabled": True,
        "disabled_reason": "Aguarda contexto real de viagens.", "title": "Acidente aéreo", "text": "Indisponível sem contexto de viagem.", "conditions": {"international_travel": True, "status": "active"}, "choices": []},
    "overdose_emergency": {"key": "overdose_emergency", "type": "health", "rarity": "legendary", "unique": True,
        "title": "Emergência médica fora de campo", "text": "Uma emergência médica durante uma noite fora exige atendimento imediato.", "conditions": {"min_age": 18, "min_reputation": {"controversy": 30}, "status": "active"},
        "choices": [{"id": "treatment", "label": "Receber tratamento", "effects": {"player": {"morale": -10, "form": -7}, "reputation": {"media": -5, "discipline": -6}, "history": "Você passou por uma emergência médica e iniciou recuperação."}}]},
    "fatal_off_field_accident": {"key": "fatal_off_field_accident", "type": "health", "rarity": "legendary", "unique": True,
        "title": "Acidente fatal fora de campo", "text": "Um acidente inesperado encerra tragicamente sua história fora do futebol.", "conditions": {"min_age": 18, "status": "active"},
        "choices": [{"id": "fatal_outcome", "label": "Encerrar a história", "effects": {"terminal": {"type": "death", "reason": "Um acidente fatal fora de campo encerrou sua trajetória."}}}]},
    "club_bankruptcy": {"key": "club_bankruptcy", "type": "career", "rarity": "very_rare", "unique": True, "disabled": True,
        "disabled_reason": "Aguarda suporte seguro a jogador sem clube.", "title": "Clube entrou em falência", "text": "Indisponível até existir suporte a jogador sem clube.", "conditions": {"status": "active"}, "choices": []},
    "leave_football": {"key": "leave_football", "type": "career", "rarity": "rare", "unique": True,
        "title": "Uma vida fora do futebol", "text": "Após uma fase longa e difícil, você considera abandonar a carreira para seguir outro caminho.", "conditions": {"min_age": 22, "max_morale": 35, "max_form": 48, "status": "active"},
        "choices": [{"id": "keep_fighting", "label": "Continuar lutando pela carreira", "effects": {"reputation": {"leadership": 2}, "player": {"morale": 3}}},
                    {"id": "leave", "label": "Abandonar o futebol", "effects": {"terminal": {"type": "retirement", "reason": "Você abandonou o futebol para seguir outra carreira."}}}]},
}
